### ISSUE TITLE
Get Daily Matchups Error

### ISSUE THREAD

**Issue by santi861** [JakeKandell/NBA-Predict#13]
Hi i am receiving this error when I try to run nbapredict.py, any help is appreciated! :)
Thank you for this amazing work btw.

$ python ./nbapredict.py
Traceback (most recent call last):
  File "./nbapredict.py", line 7, in <module>
    from getDailyMatchups import dailyMatchupsPresent
ModuleNotFoundError: No module named 'getDailyMatchups'
(base) MacBook:desktop santiagocarvajalino$

**Comment by JakeKandell** [comment]
Sorry for the late response. Do you have the repository in it's entirety on your computer? Are the files all in the same folder without being moved around? I think this issue would result if you moved the getDailyMatchups.py file which could cause it to not be found by Python.

**Comment by santi861** [comment]
Hi Jake,

Yes I have it completely downloaded on my desktop, I also re-downaloaded it twice. 

Thanks again!

**Comment by santi861** [comment]
Getting this error now. 

Traceback (most recent call last):
  File "nbapredict.py", line 95, in <module>
    makeInterpretPredictions('29/04/2021', '2020-21', '12/22/2020')
  File "nbapredict.py", line 89, in makeInterpretPredictions
    predictions = predictDailyGames(currentDate, season, startOfSeason)
  File "nbapredict.py", line 42, in predictDailyGames
    dailyGames = dailyMatchupsPresent(currentDate)  # Gets all games for specified date
  File "/Users/Desktop/NBA-Predict-master/getDailyMatchups.py", line 46, in dailyMatchupsPresent
    dailyMatchups = scoreboard.Scoreboard(league_id='00', game_date=date, headers=customHeaders, timeout=120)
  File "/opt/anaconda3/lib/python3.8/site-packages/nba_api/stats/endpoints/scoreboard.py", line 34, in __init__
    self.get_request()
  File "/opt/anaconda3/lib/python3.8/site-packages/nba_api/stats/endpoints/scoreboard.py", line 44, in get_request
    self.load_response()
  File "/opt/anaconda3/lib/python3.8/site-packages/nba_api/stats/endpoints/scoreboard.py", line 47, in load_response
    data_sets = self.nba_response.get_data_sets()
  File "/opt/anaconda3/lib/python3.8/site-packages/nba_api/stats/library/http.py", line 83, in get_data_sets
    raw_dict = self.get_dict()
  File "/opt/anaconda3/lib/python3.8/site-packages/nba_api/library/http.py", line 41, in get_dict
    return json.loads(self._response)
  File "/opt/anaconda3/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/opt/anaconda3/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/anaconda3/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by JakeKandell** [comment]
I think you have the date formatted incorrectly. Use mm/dd/yyyy format.
